from src.historical_data_fetcher.gpu_statistics.gpu_statistics_database_interactions import GpuStatisticsDatabaseInteractions

gpu_statistics_database_interactions = GpuStatisticsDatabaseInteractions()
gpu_statistics_database_interactions.update()