class Variables:
    CRYPTOID_URL_FIRST_PART = "https://chainz.cryptoid.info/"
    CRYPTOID_URL_SECOND_PART = "/block.dws?"
    ELECTRICITY_COST = 0.13

    KILO = 1000
    MEGA = 1000 * KILO
    GIGA = 1000 * MEGA

    SECOND = 1000
    MINUTE = 60 * SECOND
    HOUR = 60 * MINUTE

    GPU_STATISTICS_DATABASE_UPDATE_RATE = 1 * HOUR
    CURRENCY_HISTORICAL_DATABASE_UPDATE_RATE = 1 * HOUR
    CURRENCY_LIVE_DATABASE_UPDATE_RATE = 1 * MINUTE
